#  Credentials for using Twitter API. 
CONSUMER_KEY = "--INSERT CONSUMER KEY--"
CONSUMER_SECRET = "--INSERT CONSUMER SECRET--"

ACCESS_TOKEN = "--INSERT ACCESS TOKEN--"
ACCESS_SECRET = "--INSERT ACCESS SECRET--"
